# Melam info: family (animation), instruments, and About / Story / At festivals in English and Malayalam.
INFO = {
'panchavadyam': ('hand', 'Thimila · Maddalam · Elathalam · Edakka · Kombu · Shankh',
 ['Five instruments play together: thimila and maddalam drums, elathalam cymbals, the edakka and the kombu horn, opened by the blowing of the shankh.',
  'തിമിലയും മദ്ദളവും ഇലത്താളവും ഇടയ്ക്കയും കൊമ്പും ഒന്നിച്ചു ചേരുന്നു. ശംഖനാദത്തോടെ തുടങ്ങുന്നു.'],
 ['Its modern form was shaped in the early 20th century by temple musicians of the Thrissur and Palakkad region, who arranged it into kaalams that grow steadily faster.',
  'തൃശ്ശൂർ, പാലക്കാട് മേഖലയിലെ ക്ഷേത്രവാദ്യകലാകാരന്മാർ ഇരുപതാം നൂറ്റാണ്ടിന്റെ തുടക്കത്തിൽ ഇതിന് ഇന്നത്തെ രൂപം നൽകി. കാലങ്ങൾ കയറുംതോറും വേഗം കൂടുന്ന ഘടന.'],
 ['It leads temple processions with caparisoned elephants. The Madathil Varavu Panchavadyam at Thrissur Pooram is one of its most celebrated performances.',
  'നെറ്റിപ്പട്ടം കെട്ടിയ ആനകളോടൊപ്പമുള്ള എഴുന്നള്ളിപ്പുകൾക്ക് മുന്നിൽ. തൃശ്ശൂർ പൂരത്തിലെ മഠത്തിൽ വരവ് പഞ്ചവാദ്യം ഏറെ പ്രസിദ്ധം.']),
'pandi': ('chenda', 'Uruttu chenda · Valanthala · Veekku chenda · Elathalam · Kuzhal · Kombu',
 ['A grand chenda melam where rows of uruttu and valanthala chendas, elathalam, kuzhal and kombu build waves of sound together.',
  'ഉരുട്ടുചെണ്ടയും വലന്തലയും ഇലത്താളവും കുഴലും കൊമ്പും നിരകളായി നിന്ന് ശബ്ദത്തിരമാലകൾ തീർക്കുന്ന ചെണ്ടമേളം.'],
 ['Pandi Melam is traditionally played outside the temple walls, unlike Panchari, and is known for its raw power. The name is often linked to the Pandya country to the east.',
  'പഞ്ചാരിയിൽ നിന്ന് വ്യത്യസ്തമായി ക്ഷേത്രമതിലിനു പുറത്താണ് പരമ്പരാഗതമായി പാണ്ടിമേളം. കിഴക്കുള്ള പാണ്ഡ്യനാടുമായി ഈ പേരിനെ ബന്ധിപ്പിക്കാറുണ്ട്.'],
 ['The Ilanjithara Melam, played under the ilanji tree at Vadakkunnathan temple during Thrissur Pooram, is the most famous Pandi Melam of all.',
  'തൃശ്ശൂർ പൂരത്തിന് വടക്കുന്നാഥക്ഷേത്രത്തിലെ ഇലഞ്ഞിമരച്ചുവട്ടിൽ നടക്കുന്ന ഇലഞ്ഞിത്തറ മേളമാണ് ഏറ്റവും പ്രസിദ്ധമായ പാണ്ടിമേളം.']),
'panchari': ('chenda', 'Uruttu chenda · Valanthala · Veekku chenda · Elathalam · Kuzhal · Kombu',
 ['A six-akshara chenda melam that moves through kaalams, each one tightening the rhythm until the final kalasam.',
  'ആറ് അക്ഷരകാലമുള്ള ചെണ്ടമേളം. ഓരോ കാലത്തിലും താളം മുറുകി കലാശത്തിലെത്തുന്നു.'],
 ['Panchari is regarded as the most classical of the chenda melams and is played inside the temple precincts.',
  'ചെണ്ടമേളങ്ങളിൽ ഏറ്റവും ശാസ്ത്രീയമായി കരുതപ്പെടുന്നത് പഞ്ചാരിയാണ്. ക്ഷേത്രമതിൽക്കകത്താണ് ഇത് കൊട്ടുന്നത്.'],
 ['It accompanies the seeveli processions of temple festivals. Peruvanam Pooram is especially famous for its Panchari Melam.',
  'ക്ഷേത്രോത്സവങ്ങളിലെ ശീവേലി എഴുന്നള്ളിപ്പുകൾക്ക് അകമ്പടി. പെരുവനം പൂരത്തിലെ പഞ്ചാരിമേളം ഏറെ പ്രസിദ്ധം.']),
'thayambaka': ('chenda', 'Lead chenda · Valanthala · Elathalam',
 ['A solo chenda performance where the lead player improvises over a steady base of valanthala and elathalam.',
  'വലന്തലയുടെയും ഇലത്താളത്തിന്റെയും ഉറച്ച താളത്തിനു മുകളിൽ പ്രധാന ചെണ്ടക്കാരൻ മനോധർമ്മം കാണിക്കുന്ന ഏകവാദന കല.'],
 ['Thayambaka grew as a temple offering and became the stage where great chenda artists show their imagination, moving from slow pathikaalam to blazing speed.',
  'ക്ഷേത്ര വഴിപാടായി വളർന്ന തായമ്പക, പതികാലത്തിൽ തുടങ്ങി അതിദ്രുതത്തിലെത്തുന്ന ചെണ്ടക്കാരന്റെ ഭാവനയുടെ വേദിയാണ്.'],
 ['It is usually played at night during temple festivals, often as a devotee’s offering. Double and triple thayambaka bring several lead players together.',
  'ഉത്സവരാത്രികളിൽ, പലപ്പോഴും ഭക്തരുടെ വഴിപാടായി. ഇരട്ട, ട്രിപ്പിൾ തായമ്പകകളിൽ ഒന്നിലധികം പ്രധാനവാദകർ ഒന്നിക്കുന്നു.']),
'keli': ('chenda', 'Chenda · Maddalam · Chengila · Elathalam',
 ['The drum prelude of Kathakali, played by chenda, maddalam, chengila and elathalam.',
  'ചെണ്ട, മദ്ദളം, ചേങ്ങില, ഇലത്താളം എന്നിവ ചേർന്ന കഥകളിയുടെ ആമുഖ കൊട്ട്.'],
 ['In the days before posters, the sound of Keli carried across the village at dusk to tell everyone that Kathakali would be performed that night.',
  'പോസ്റ്ററുകൾക്കു മുമ്പുള്ള കാലത്ത്, അന്നു രാത്രി കഥകളിയുണ്ടെന്ന് സന്ധ്യയ്ക്ക് നാടാകെ അറിയിച്ചിരുന്നത് കേളിയുടെ മുഴക്കമാണ്.'],
 ['Played in the temple grounds or outside the performance venue in the evening before a Kathakali night.',
  'കഥകളി നടക്കുന്ന ദിവസം സന്ധ്യയ്ക്ക് ക്ഷേത്രപ്പറമ്പിലോ അരങ്ങിനു പുറത്തോ കൊട്ടുന്നു.']),
'sopanam': ('edakka', 'Voice · Edakka',
 ['Devotional singing with the edakka, performed on the sopanam, the steps leading to the temple sanctum.',
  'ശ്രീകോവിലിലേക്കുള്ള സോപാനപ്പടിയിൽ ഇടയ്ക്ക കൊട്ടി പാടുന്ന ഭക്തിസംഗീതം.'],
 ['Sopana Sangeetham grew from the singing of Jayadeva’s Ashtapadi in Kerala temples. Njeralathu Rama Poduval brought it to wide audiences in the 20th century.',
  'കേരളക്ഷേത്രങ്ങളിലെ അഷ്ടപദി ആലാപനത്തിൽ നിന്ന് വളർന്നതാണ് സോപാനസംഗീതം. ഞെരളത്ത് രാമപ്പൊതുവാൾ ഇതിനെ ജനങ്ങളിലേക്ക് എത്തിച്ചു.'],
 ['Sung during the evening deeparadhana and special poojas, when the sanctum doors open and the lamps are waved.',
  'സന്ധ്യയ്ക്ക് നട തുറന്ന് ദീപാരാധന നടക്കുമ്പോഴും വിശേഷാൽ പൂജകൾക്കും പാടുന്നു.']),
'chempada': ('chenda', 'Uruttu chenda · Valanthala · Veekku chenda · Elathalam · Kombu',
 ['A chenda melam set in Chempada thalam, the eight-akshara cycle at the heart of many Kerala rhythms.',
  'കേരളത്തിലെ പല താളങ്ങളുടെയും അടിസ്ഥാനമായ എട്ട് അക്ഷരമുള്ള ചെമ്പട താളത്തിലുള്ള ചെണ്ടമേളം.'],
 ['Chempada is one of the classic thalams of temple music, and its melam moves through kaalams like Panchari.',
  'ക്ഷേത്രവാദ്യത്തിലെ പ്രധാന താളങ്ങളിൽ ഒന്നാണ് ചെമ്പട. പഞ്ചാരിയെപ്പോലെ കാലങ്ങളിലൂടെ മുന്നേറുന്നു.'],
 ['Played for festival processions and temple rituals, often by the same masters who lead Panchari.',
  'ഉത്സവ എഴുന്നള്ളിപ്പുകൾക്കും ക്ഷേത്രചടങ്ങുകൾക്കും; പലപ്പോഴും പഞ്ചാരി നയിക്കുന്ന അതേ ആചാര്യന്മാർ.']),
'adantha': ('chenda', 'Chenda · Elathalam · Kombu',
 ['A slow, stately chenda melam in Adantha thalam, a long fourteen-akshara cycle.',
  'പതിനാല് അക്ഷരമുള്ള അടന്ത താളത്തിൽ, പതിഞ്ഞതും ഗാംഭീര്യമുള്ളതുമായ ചെണ്ടമേളം.'],
 ['Adantha is one of the older temple melams, heard less often today than Panchari and Pandi.',
  'പഞ്ചാരിയും പാണ്ടിയും പോലെ ഇന്ന് അധികം കേൾക്കാത്ത, പഴയ ക്ഷേത്രമേളങ്ങളിൽ ഒന്നാണ് അടന്ത.'],
 ['Played during temple rituals and processions where a calm, dignified rhythm suits the occasion.',
  'ശാന്തവും ഗൗരവമുള്ളതുമായ താളം ആവശ്യമുള്ള ക്ഷേത്രചടങ്ങുകളിലും എഴുന്നള്ളിപ്പുകളിലും.']),
'anchadantha': ('chenda', 'Chenda · Elathalam',
 ['A chenda melam in Anchadantha thalam, one of the rarer temple thalams.',
  'അപൂർവമായി കേൾക്കുന്ന അഞ്ചടന്ത താളത്തിലുള്ള ചെണ്ടമേളം.'],
 ['Kerala temple drumming keeps several old thalams alive, and Anchadantha is one that only a few melams still use.',
  'കേരള ക്ഷേത്രവാദ്യം സംരക്ഷിച്ചുവരുന്ന പഴയ താളങ്ങളിൽ ഒന്നാണ് അഞ്ചടന്ത; ഇന്ന് ചുരുക്കം മേളങ്ങളിൽ മാത്രം.'],
 ['Heard at temple festivals where traditional melams are preserved and performed in full.',
  'പരമ്പരാഗത മേളങ്ങൾ പൂർണ്ണരൂപത്തിൽ അവതരിപ്പിക്കുന്ന ക്ഷേത്രോത്സവങ്ങളിൽ.']),
'dhruva': ('chenda', 'Chenda · Elathalam',
 ['A chenda melam in Dhruva thalam, one of the seven classical thalams.',
  'സപ്തതാളങ്ങളിൽ ഒന്നായ ധ്രുവ താളത്തിലുള്ള ചെണ്ടമേളം.'],
 ['Dhruva comes from the classical system of seven thalams, which Kerala temple music adapted to the chenda.',
  'സപ്തതാള സമ്പ്രദായത്തിലെ ധ്രുവ താളം കേരള ക്ഷേത്രവാദ്യം ചെണ്ടയിലേക്ക് സ്വീകരിച്ചു.'],
 ['A rare melam, played at temple festivals that keep the older thalams in use.',
  'പഴയ താളങ്ങൾ നിലനിർത്തുന്ന ക്ഷേത്രോത്സവങ്ങളിൽ കേൾക്കാവുന്ന അപൂർവ മേളം.']),
'champa': ('chenda', 'Chenda · Elathalam',
 ['A chenda melam in Champa thalam, a ten-akshara cycle.',
  'പത്ത് അക്ഷരമുള്ള ചമ്പ താളത്തിലുള്ള ചെണ്ടമേളം.'],
 ['Champa thalam is also used in Kathakali music, linking the temple melam to the stage.',
  'കഥകളി സംഗീതത്തിലും ചമ്പ താളം ഉപയോഗിക്കുന്നു; ക്ഷേത്രമേളത്തെ അരങ്ങുമായി ബന്ധിപ്പിക്കുന്നു.'],
 ['Played at temple festivals as one of the traditional melams.',
  'ക്ഷേത്രോത്സവങ്ങളിൽ പരമ്പരാഗത മേളങ്ങളിൽ ഒന്നായി.']),
'shinkari': ('chenda', 'Chenda · Elathalam',
 ['A fast, energetic chenda melam with catchy patterns that crowds love to dance to.',
  'ആളുകൾ ചുവടുവെക്കുന്ന, വേഗമേറിയ ആവേശമുള്ള ചെണ്ടമേളം.'],
 ['Shinkari Melam grew in popularity in the late 20th century as a lively, flexible form played outside temple rules.',
  'ഇരുപതാം നൂറ്റാണ്ടിന്റെ അവസാനം ക്ഷേത്രനിയമങ്ങൾക്ക് പുറത്ത്, എവിടെയും കൊട്ടാവുന്ന ജനകീയ മേളമായി ശിങ്കാരിമേളം വളർന്നു.'],
 ['Heard at weddings, processions, sports days, rallies and Onam celebrations across Kerala.',
  'കല്യാണങ്ങൾ, ഘോഷയാത്രകൾ, കായികമേളകൾ, ഓണാഘോഷങ്ങൾ എന്നിവിടങ്ങളിൽ.']),
'kombupattu': ('horn', 'Kombu · Elathalam',
 ['Rows of kombu, the curved brass horn, call and answer each other over elathalam.',
  'വളഞ്ഞ ഓട്ടുകൊമ്പുകൾ നിരയായി നിന്ന് ഇലത്താളത്തിനു മുകളിൽ പരസ്പരം വിളിച്ചുചൊല്ലുന്നു.'],
 ['The kombu has a limited set of notes, so kombu players build their music from patterns and timing passed down through families.',
  'കൊമ്പിന് കുറച്ചു സ്വരങ്ങളേ ഉള്ളൂ; കുടുംബപരമ്പരയായി കൈമാറുന്ന രീതികളിലൂടെയും താളത്തിലൂടെയുമാണ് ഈ സംഗീതം.'],
 ['Kombu Pattu is performed as its own item at temple festivals, and kombu players also join Panchavadyam and Pandi Melam.',
  'ക്ഷേത്രോത്സവങ്ങളിൽ പ്രത്യേക ഇനമായി; കൊമ്പുകാർ പഞ്ചവാദ്യത്തിലും പാണ്ടിമേളത്തിലും ചേരുന്നു.']),
'kuzhalpattu': ('pipe', 'Kuzhal · Elathalam',
 ['Kuzhal, Kerala’s double-reed pipe, played with elathalam keeping the thalam.',
  'കേരളത്തിന്റെ ഇരട്ടനാവുള്ള കുഴൽ, ഇലത്താളം താളം പിടിക്കുന്നു.'],
 ['The kuzhal gives the melam its melodic thread, and Kuzhal Pattu lets that sound take the lead.',
  'മേളത്തിന് ഈണം നൽകുന്നത് കുഴലാണ്; കുഴൽപറ്റിൽ ആ നാദം മുന്നിൽ നിൽക്കുന്നു.'],
 ['Played at temple festivals as a separate item, and kuzhal players join the great chenda melams.',
  'ക്ഷേത്രോത്സവങ്ങളിൽ പ്രത്യേക ഇനമായും വലിയ ചെണ്ടമേളങ്ങളുടെ ഭാഗമായും.']),
'nadaswaram': ('pipe', 'Nadaswaram · Thavil · Shruti',
 ['The long double-reed nadaswaram with the barrel-shaped thavil drum.',
  'നീണ്ട നാദസ്വരവും വീപ്പയാകൃതിയുള്ള തകിലും.'],
 ['The nadaswaram tradition came from Tamil temple music and became part of temple life in southern Kerala.',
  'തമിഴ് ക്ഷേത്രസംഗീതത്തിൽ നിന്നെത്തിയ നാദസ്വരം തെക്കൻ കേരളത്തിലെ ക്ഷേത്രജീവിതത്തിന്റെ ഭാഗമായി.'],
 ['Played during temple processions, morning rituals and Hindu weddings.',
  'ക്ഷേത്ര എഴുന്നള്ളിപ്പുകളിലും പുലർകാല ചടങ്ങുകളിലും കല്യാണങ്ങളിലും.']),
'mizhavu': ('hand', 'Mizhavu · Kuzhithalam',
 ['A large copper pot drum played with the hands, with small kuzhithalam cymbals.',
  'കൈകൊണ്ട് കൊട്ടുന്ന ചെമ്പുകൊണ്ടുള്ള വലിയ കുടം പോലെയുള്ള വാദ്യം, കൂടെ കുഴിത്താളം.'],
 ['The mizhavu is traditionally played by the Nambiar community and treated as sacred, kept inside the temple koothambalam.',
  'നമ്പ്യാർ സമുദായമാണ് പരമ്പരാഗതമായി മിഴാവ് വായിക്കുന്നത്; ക്ഷേത്രക്കൂത്തമ്പലത്തിൽ സൂക്ഷിക്കുന്ന പവിത്ര വാദ്യം.'],
 ['Accompanies Koodiyattam and Chakyar Koothu in temple theatres during festival seasons.',
  'ഉത്സവകാലത്ത് കൂത്തമ്പലങ്ങളിൽ കൂടിയാട്ടത്തിനും ചാക്യാർകൂത്തിനും അകമ്പടി.']),
'irattathayambaka': ('chenda', 'Two lead chendas · Valanthala · Elathalam',
 ['Thayambaka with two lead chenda players who answer and challenge each other.',
  'രണ്ടു പ്രധാന ചെണ്ടക്കാർ പരസ്പരം മറുപടിയും വെല്ലുവിളിയുമായി കൊട്ടുന്ന തായമ്പക.'],
 ['Pairing two masters became a festival favourite, turning the solo into a musical conversation.',
  'രണ്ട് ആചാര്യന്മാരെ ഒന്നിപ്പിച്ചതോടെ ഏകവാദനം സംഗീതസംവാദമായി; ഉത്സവങ്ങളിൽ ഏറെ ജനപ്രിയം.'],
 ['A highlight of festival nights, drawing large crowds of thayambaka lovers.',
  'ഉത്സവരാത്രികളിലെ പ്രധാന ആകർഷണം; തായമ്പക ആസ്വാദകരുടെ വലിയ കൂട്ടം.']),
'kathakalimelam': ('chenda', 'Chenda · Maddalam · Chengila · Elathalam',
 ['The percussion of Kathakali: chenda and maddalam with chengila and elathalam played by the singers.',
  'കഥകളിയുടെ വാദ്യം: ചെണ്ടയും മദ്ദളവും, പാട്ടുകാർ വായിക്കുന്ന ചേങ്ങിലയും ഇലത്താളവും.'],
 ['The chenda gives voice to fierce and heroic characters, while the maddalam carries the steady flow of the story.',
  'വീരരും രൗദ്രരുമായ കഥാപാത്രങ്ങൾക്ക് ചെണ്ട ശബ്ദം നൽകുന്നു; കഥയുടെ ഒഴുക്ക് മദ്ദളം നിലനിർത്തുന്നു.'],
 ['Heard through all-night Kathakali performances at temple festivals.',
  'ക്ഷേത്രോത്സവങ്ങളിലെ രാത്രി മുഴുവൻ നീളുന്ന കഥകളികളിൽ.']),
'theyyam': ('mask', 'Chenda · Elathalam · Kuzhal',
 ['The chenda rhythms that drive Theyyam, where performers become living deities.',
  'കോലധാരി ദൈവമായി മാറുന്ന തെയ്യത്തെ ഉണർത്തുന്ന ചെണ്ടത്താളം.'],
 ['Theyyam is an ancient ritual of north Malabar with hundreds of forms, each with its own story, costume and songs.',
  'നൂറുകണക്കിന് രൂപങ്ങളുള്ള, ഓരോന്നിനും സ്വന്തം കഥയും വേഷവും തോറ്റവുമുള്ള ഉത്തരമലബാറിലെ പ്രാചീന അനുഷ്ഠാനം.'],
 ['Performed in kavus and village shrines through the Theyyam season, from late autumn to early summer.',
  'തെയ്യക്കാലത്ത് കാവുകളിലും തറവാട്ടുസ്ഥാനങ്ങളിലും.']),
'padayani': ('mask', 'Thappu · Chenda · Voice',
 ['Thappu drums and songs accompany giant painted kolams made from areca palm sheaths.',
  'കമുകിൻപാളയിൽ വരച്ചുണ്ടാക്കിയ വലിയ കോലങ്ങൾക്ക് തപ്പും പാട്ടും അകമ്പടി.'],
 ['Padayani is linked to the story of Bhadrakali, and the kolams are believed to calm the goddess after her battle with Darika.',
  'ദാരികവധത്തിനു ശേഷം ഭദ്രകാളിയെ ശാന്തയാക്കാനാണ് കോലങ്ങൾ എന്നാണ് വിശ്വാസം.'],
 ['Held at Bhagavathi temples of central Travancore, especially around Pathanamthitta, over several nights.',
  'മധ്യതിരുവിതാംകൂറിലെ, പ്രത്യേകിച്ച് പത്തനംതിട്ടയിലെ ഭഗവതിക്ഷേത്രങ്ങളിൽ പല രാത്രികളിലായി.']),
'mudiyettu': ('mask', 'Chenda · Elathalam · Kuzhal',
 ['A ritual drama of the battle between Kali and the demon Darika, with chenda and fiery masks.',
  'കാളിയും ദാരികനും തമ്മിലുള്ള യുദ്ധം ചെണ്ടയും ഉഗ്രമായ മുടികളുമായി അവതരിപ്പിക്കുന്ന അനുഷ്ഠാന നാടകം.'],
 ['Mudiyettu was recognised by UNESCO as Intangible Cultural Heritage of Humanity in 2010.',
  '2010-ൽ യുനെസ്കോ മാനവരാശിയുടെ അദൃശ്യ സാംസ്കാരിക പൈതൃകമായി മുടിയേറ്റിനെ അംഗീകരിച്ചു.'],
 ['Performed in Bhadrakali temples of central Kerala, traditionally after the harvest.',
  'മധ്യകേരളത്തിലെ ഭദ്രകാളിക്ഷേത്രങ്ങളിൽ, പരമ്പരാഗതമായി വിളവെടുപ്പിനു ശേഷം.']),
'ashtapadi': ('edakka', 'Voice · Edakka',
 ['Jayadeva’s Gita Govinda sung in the Sopanam style with the edakka.',
  'ജയദേവരുടെ ഗീതഗോവിന്ദം ഇടയ്ക്കയോടെ സോപാനരീതിയിൽ.'],
 ['The Gita Govinda, written in the 12th century, reached Kerala temples and found a new voice in the Sopanam tradition.',
  'പന്ത്രണ്ടാം നൂറ്റാണ്ടിൽ രചിച്ച ഗീതഗോവിന്ദം കേരളക്ഷേത്രങ്ങളിലെത്തി സോപാനരീതിയിൽ പുതിയ ശബ്ദം കണ്ടെത്തി.'],
 ['Sung at the sanctum during poojas, famously at Guruvayur temple.',
  'പൂജാസമയത്ത് ശ്രീകോവിൽ നടയിൽ; ഗുരുവായൂരിൽ പ്രസിദ്ധം.']),
'pulluvanpattu': ('hand', 'Pulluvan veena · Kudam · Voice',
 ['Songs of the Pulluvar played on the one-string pulluvan veena and the pot-shaped kudam.',
  'ഒറ്റക്കമ്പിയുള്ള പുള്ളുവൻ വീണയും കുടവുമായി പുള്ളുവർ പാടുന്ന പാട്ടുകൾ.'],
 ['The Pulluvar sing to the serpent gods, and their songs are believed to bring blessings and protection to the household.',
  'പുള്ളുവർ നാഗദൈവങ്ങളെ പാടി പ്രസാദിപ്പിക്കുന്നു; വീടിന് ഐശ്വര്യവും സംരക്ഷണവും എന്നാണ് വിശ്വാസം.'],
 ['Heard at sarpakkavus (serpent groves), in homes and during Sarpam Thullal rituals.',
  'സർപ്പക്കാവുകളിലും വീടുകളിലും സർപ്പംതുള്ളലിലും.']),
'duffmuttu': ('hand', 'Daf · Voice',
 ['A Mappila art form in which performers beat the daf, a round frame drum, while singing.',
  'ദഫ് എന്ന വട്ടത്തിലുള്ള ചട്ടവാദ്യം കൊട്ടി പാടുന്ന മാപ്പിള കലാരൂപം.'],
 ['Duff Muttu came to Malabar with Arab trade links and grew within the Mappila Muslim community.',
  'അറബ് വ്യാപാരബന്ധങ്ങളിലൂടെ മലബാറിലെത്തി മാപ്പിള മുസ്‌ലിം സമൂഹത്തിൽ വളർന്ന കല.'],
 ['Performed at weddings, uroos festivals and community celebrations, and on school youth festival stages.',
  'കല്യാണങ്ങൾ, ഉറൂസുകൾ, സമൂഹാഘോഷങ്ങൾ, സ്കൂൾ കലോത്സവ വേദികൾ.']),
'arabanamuttu': ('hand', 'Arabana · Voice',
 ['Performers in rows play the arabana, a wide wooden frame drum, while singing.',
  'നിരകളായി നിന്ന് അറബന എന്ന വീതിയുള്ള ചട്ടവാദ്യം കൊട്ടി പാടുന്നു.'],
 ['Arabana Muttu is a Mappila art from Malabar, with songs that praise prophets and saints.',
  'പ്രവാചകരെയും സൂഫിവര്യരെയും പ്രകീർത്തിക്കുന്ന പാട്ടുകളുള്ള മലബാറിലെ മാപ്പിള കല.'],
 ['Performed at religious festivals, weddings and youth festival stages.',
  'മതാഘോഷങ്ങളിലും കല്യാണങ്ങളിലും കലോത്സവങ്ങളിലും.']),
'kolkali': ('sticks', 'Kol (sticks) · Voice',
 ['Dancers in a circle strike short sticks together in rhythm while singing.',
  'വട്ടത്തിൽ നിന്ന് പാട്ടോടൊപ്പം ചെറിയ കോലുകൾ താളത്തിൽ കൂട്ടിമുട്ടിക്കുന്ന കളി.'],
 ['Kolkali is popular across Kerala and especially loved in Malabar, where Mappila Kolkali has its own songs.',
  'കേരളമാകെ പ്രചാരമുള്ള കോൽക്കളി മലബാറിൽ ഏറെ പ്രിയം; മാപ്പിള കോൽക്കളിക്ക് സ്വന്തം പാട്ടുകളുണ്ട്.'],
 ['Performed at festivals, harvest celebrations and school youth festivals.',
  'ഉത്സവങ്ങളിലും വിളവെടുപ്പ് ആഘോഷങ്ങളിലും കലോത്സവങ്ങളിലും.']),
'ottamthullal': ('hand', 'Maddalam or mridangam · Elathalam · Voice',
 ['A solo performer sings and dances satirical stories, with maddalam or mridangam and elathalam.',
  'മദ്ദളത്തിന്റെയോ മൃദംഗത്തിന്റെയോ ഇലത്താളത്തിന്റെയോ അകമ്പടിയോടെ ഒരാൾ ഹാസ്യകഥകൾ പാടിയാടുന്നു.'],
 ['Kunchan Nambiar created Ottamthullal in the 18th century, using humour to poke fun at the powerful of his day.',
  'പതിനെട്ടാം നൂറ്റാണ്ടിൽ കുഞ്ചൻ നമ്പ്യാർ രൂപം നൽകിയ ഓട്ടൻതുള്ളൽ, അക്കാലത്തെ അധികാരികളെ ഹാസ്യത്തിലൂടെ വിമർശിച്ചു.'],
 ['Performed on temple festival stages and at youth festivals.',
  'ക്ഷേത്രോത്സവ വേദികളിലും കലോത്സവങ്ങളിലും.']),
'krishnanattam': ('hand', 'Maddalam · Chenda · Elathalam · Voice',
 ['A dance drama of Krishna’s life performed over eight nights.',
  'എട്ടു രാത്രികളിലായി ശ്രീകൃഷ്ണന്റെ ജീവിതം അവതരിപ്പിക്കുന്ന നൃത്തനാടകം.'],
 ['It was created in the 17th century by Manaveda, the Zamorin of Kozhikode, and is now maintained by Guruvayur Devaswom.',
  'പതിനേഴാം നൂറ്റാണ്ടിൽ കോഴിക്കോട് സാമൂതിരി മാനവേദൻ രചിച്ചു; ഇന്ന് ഗുരുവായൂർ ദേവസ്വം സംരക്ഷിക്കുന്നു.'],
 ['Performed at Guruvayur temple as a devotee’s offering.',
  'ഗുരുവായൂർ ക്ഷേത്രത്തിൽ ഭക്തരുടെ വഴിപാടായി.']),
'chakyarkoothu': ('hand', 'Mizhavu · Kuzhithalam · Voice',
 ['A Chakyar retells puranic stories with wit and sharp comments, accompanied by the mizhavu.',
  'മിഴാവിന്റെ അകമ്പടിയോടെ ചാക്യാർ പുരാണകഥകൾ നർമ്മവും വിമർശനവും ചേർത്ത് അവതരിപ്പിക്കുന്നു.'],
 ['Koothu is one of Kerala’s oldest theatre forms, traditionally performed in temple theatres called koothambalams.',
  'കേരളത്തിലെ ഏറ്റവും പഴയ നാടകരൂപങ്ങളിൽ ഒന്ന്; കൂത്തമ്പലങ്ങളിലാണ് പരമ്പരാഗതമായി.'],
 ['Performed during temple festivals over several days.',
  'ക്ഷേത്രോത്സവങ്ങളിൽ പല ദിവസങ്ങളിലായി.']),
'kottippadi': ('edakka', 'Voice · Edakka',
 ['Devotional songs sung with the edakka at the sanctum steps.',
  'ശ്രീകോവിൽ നടയിൽ ഇടയ്ക്ക കൊട്ടി പാടുന്ന ഭക്തിഗീതങ്ങൾ.'],
 ['Kottippadi Seva is a service performed by temple musicians, closely tied to the Sopanam tradition.',
  'ക്ഷേത്രകലാകാരന്മാർ നടത്തുന്ന സേവ; സോപാന പാരമ്പര്യവുമായി അടുത്ത ബന്ധം.'],
 ['Offered during poojas and festival days in temples.',
  'ക്ഷേത്രങ്ങളിലെ പൂജാസമയത്തും ഉത്സവദിവസങ്ങളിലും.']),
'kalamezhuthu': ('lamp', 'Nanthuni · Elathalam · Voice',
 ['Songs sung beside a kalam, a floor drawing of a deity made with five natural colour powders.',
  'അഞ്ചു പ്രകൃതിദത്ത നിറപ്പൊടികൾ കൊണ്ട് വരച്ച ദേവതാകളത്തിനരികെ പാടുന്ന പാട്ടുകൾ.'],
 ['The kalam is drawn by hand over hours and erased at the end of the ritual.',
  'മണിക്കൂറുകളെടുത്ത് കൈകൊണ്ട് വരയ്ക്കുന്ന കളം ചടങ്ങിനൊടുവിൽ മായ്ക്കുന്നു.'],
 ['Held for Bhadrakali, Ayyappan and the serpent gods in temples and homes.',
  'ഭദ്രകാളി, അയ്യപ്പൻ, നാഗദൈവങ്ങൾ എന്നിവർക്കായി ക്ഷേത്രങ്ങളിലും വീടുകളിലും.']),
'ayyappanpattu': ('edakka', 'Udukku · Voice',
 ['Songs about Ayyappan sung to the beat of the udukku, a small hourglass drum.',
  'ഉടുക്ക് എന്ന ചെറിയ ഡമരുവിന്റെ താളത്തിൽ പാടുന്ന അയ്യപ്പൻ പാട്ടുകൾ.'],
 ['The songs tell the story of Ayyappan’s birth and deeds and are sung through the night.',
  'അയ്യപ്പന്റെ ജനനവും വീരകഥകളും പാടുന്നു; രാത്രി മുഴുവൻ നീളാം.'],
 ['Heard in the Mandalam season before the Sabarimala pilgrimage and at Ayyappan temple festivals.',
  'ശബരിമല തീർത്ഥാടനത്തിനു മുമ്പുള്ള മണ്ഡലകാലത്തും അയ്യപ്പക്ഷേത്രോത്സവങ്ങളിലും.']),
'garudanthookkam': ('mask', 'Chenda · Elathalam',
 ['Dancers dressed as Garuda, the eagle, perform a ritual dance to the chenda.',
  'ഗരുഡവേഷം കെട്ടിയവർ ചെണ്ടയുടെ താളത്തിൽ ആടുന്ന അനുഷ്ഠാനനൃത്തം.'],
 ['It is offered to Bhadrakali, and in its traditional form the Garuda is raised high on a frame.',
  'ഭദ്രകാളിക്കുള്ള വഴിപാട്; പരമ്പരാഗതരൂപത്തിൽ ഗരുഡനെ ചട്ടത്തിൽ ഉയർത്തുന്നു.'],
 ['Performed at Kali temples of central and southern Kerala during festival season.',
  'മധ്യ-തെക്കൻ കേരളത്തിലെ കാളിക്ഷേത്രങ്ങളിൽ ഉത്സവകാലത്ത്.']),
'thira': ('mask', 'Chenda · Elathalam · Kuzhal',
 ['A ritual dance of Malabar, close to Theyyam, set to chenda.',
  'തെയ്യത്തോട് അടുത്തുനിൽക്കുന്ന, ചെണ്ടയുടെ താളത്തിൽ ആടുന്ന മലബാറിലെ അനുഷ്ഠാനനൃത്തം.'],
 ['Thira performers wear tall headdresses and become the deity for the duration of the ritual.',
  'ഉയർന്ന മുടി അണിഞ്ഞ കോലധാരി ചടങ്ങിനിടെ ദേവതയായി മാറുന്നു.'],
 ['Held at village shrines and temples in Malabar during festival season.',
  'ഉത്സവകാലത്ത് മലബാറിലെ കാവുകളിലും ക്ഷേത്രങ്ങളിലും.']),
'pulikali': ('tiger', 'Thakil · Udukku · Chenda',
 ['Performers painted as tigers dance through the streets to thakil, udukku and chenda.',
  'പുലിവേഷം ചായം തേച്ച കലാകാരന്മാർ തകിൽ, ഉടുക്ക്, ചെണ്ട താളത്തിൽ തെരുവിലൂടെ ചുവടുവെക്കുന്നു.'],
 ['Each team spends many hours painting tiger stripes, spots and faces onto the dancers’ bodies.',
  'ഓരോ സംഘവും മണിക്കൂറുകളെടുത്ത് ശരീരത്തിൽ പുലിവരകളും മുഖങ്ങളും വരയ്ക്കുന്നു.'],
 ['The big Pulikali takes place in Thrissur on the fourth day of Onam, around Swaraj Round.',
  'നാലാം ഓണത്തിന് തൃശ്ശൂർ സ്വരാജ് റൗണ്ടിൽ പ്രസിദ്ധമായ പുലിക്കളി.']),
'vanchipattu': ('boat', 'Voice · Rhythm of the oars',
 ['Rowing songs sung in call and response, keeping the oars in time.',
  'തുഴകൾ ഒരേ താളത്തിൽ വീഴാൻ ഏറ്റുപാടുന്ന തുഴച്ചിൽപ്പാട്ട്.'],
 ['Ramapurathu Warrier’s 18th-century Kuchela Vritham Vanchipattu is the best-known work in this form.',
  'രാമപുരത്തു വാര്യരുടെ പതിനെട്ടാം നൂറ്റാണ്ടിലെ കുചേലവൃത്തം വഞ്ചിപ്പാട്ടാണ് ഏറ്റവും പ്രസിദ്ധം.'],
 ['Sung during snake boat races such as Aranmula and the Nehru Trophy, around Onam.',
  'ഓണക്കാലത്തെ ആറന്മുള, നെഹ്‌റു ട്രോഫി തുടങ്ങിയ വള്ളംകളികളിൽ.']),
'thiruvathirakali': ('dance', 'Voice · Hand claps',
 ['Women dance in a circle around a lit nilavilakku, singing and clapping.',
  'കത്തിച്ച നിലവിളക്കിനു ചുറ്റും സ്ത്രീകൾ പാട്ടും കൈകൊട്ടുമായി വട്ടത്തിൽ ആടുന്നു.'],
 ['It is linked to Thiruvathira, the festival of Shiva and Parvati in the month of Dhanu.',
  'ധനുമാസത്തിലെ ശിവ-പാർവതി ഉത്സവമായ തിരുവാതിരയുമായി ബന്ധപ്പെട്ടത്.'],
 ['Danced on Thiruvathira night, during Onam and at cultural festivals.',
  'തിരുവാതിര രാത്രിയിലും ഓണക്കാലത്തും കലാമേളകളിലും.']),
'kummattikali': ('mask', 'Voice · Onavillu',
 ['Masked dancers covered in grass go from house to house singing folk songs.',
  'പുല്ലു ചുറ്റി മുഖംമൂടി അണിഞ്ഞവർ നാടൻപാട്ടുമായി വീടുതോറും കയറുന്നു.'],
 ['The masks show gods, characters from the epics and village figures, and children follow the group around.',
  'ദേവന്മാരും ഇതിഹാസകഥാപാത്രങ്ങളും ഗ്രാമീണരും മുഖംമൂടികളാകുന്നു; കുട്ടികൾ പിന്നാലെ കൂടുന്നു.'],
 ['A part of Onam in Thrissur and Palakkad districts.',
  'തൃശ്ശൂർ, പാലക്കാട് ജില്ലകളിലെ ഓണാഘോഷത്തിന്റെ ഭാഗം.']),
'margamkali': ('dance', 'Voice · Small cymbals',
 ['Dancers move in a circle around a lamp, singing with small cymbals.',
  'വിളക്കിനു ചുറ്റും ചെറിയ താളവുമായി പാടി വട്ടത്തിൽ ആടുന്നു.'],
 ['Margamkali belongs to Kerala’s Saint Thomas Christians, and its songs tell of the journey of the apostle Thomas.',
  'കേരളത്തിലെ മാർത്തോമ്മാ ക്രിസ്ത്യാനികളുടെ കലാരൂപം; തോമാശ്ലീഹായുടെ യാത്രയാണ് പാട്ടുകളിൽ.'],
 ['Performed at church festivals, weddings and youth festivals.',
  'പള്ളിപ്പെരുന്നാളുകളിലും കല്യാണങ്ങളിലും കലോത്സവങ്ങളിലും.']),
'oppana': ('dance', 'Voice · Hand claps',
 ['Women sit or move around the bride, singing and clapping in rhythm.',
  'മണവാട്ടിക്കു ചുറ്റുമിരുന്ന് സ്ത്രീകൾ താളത്തിൽ കൈകൊട്ടി പാടുന്നു.'],
 ['Oppana is the joyful wedding song of the Mappila community of Malabar.',
  'മലബാറിലെ മാപ്പിള സമൂഹത്തിന്റെ ആഹ്ലാദം നിറഞ്ഞ കല്യാണപ്പാട്ട്.'],
 ['Performed on the eve of weddings and on youth festival stages.',
  'കല്യാണത്തലേന്നും കലോത്സവ വേദികളിലും.']),
'chavittunadakam': ('dance', 'Voice · Stamping feet · Drums',
 ['A musical drama in which actors stamp out rhythms on a wooden stage.',
  'മരപ്പലകയിൽ ചുവടുകൾ ചവിട്ടി താളമിടുന്ന സംഗീതനാടകം.'],
 ['Chavittu Nadakam began among Latin Christians in the Portuguese era and tells stories of heroes such as Charlemagne.',
  'പോർച്ചുഗീസ് കാലത്ത് ലത്തീൻ ക്രിസ്ത്യാനികൾക്കിടയിൽ രൂപംകൊണ്ടു; കാറൽമാൻ ചക്രവർത്തിയെപ്പോലുള്ള വീരന്മാരുടെ കഥകൾ.'],
 ['Staged at church festivals along the coast around Kochi and Kodungallur.',
  'കൊച്ചി, കൊടുങ്ങല്ലൂർ തീരങ്ങളിലെ പള്ളിപ്പെരുന്നാളുകളിൽ.']),
'nadanpattu': ('dance', 'Voice · Thudi · Para · Village drums',
 ['Folk songs of Kerala’s farming communities, sung with village drums.',
  'ഗ്രാമീണ വാദ്യങ്ങളോടൊപ്പം പാടുന്ന കേരളത്തിലെ കർഷകസമൂഹങ്ങളുടെ നാടൻപാട്ടുകൾ.'],
 ['These songs were sung while sowing, harvesting and at rituals, carrying local history from one generation to the next.',
  'വിത്തിടുമ്പോഴും കൊയ്യുമ്പോഴും ചടങ്ങുകളിലും പാടിയിരുന്ന പാട്ടുകൾ നാടിന്റെ ചരിത്രം തലമുറകളിലേക്ക് കൈമാറി.'],
 ['Heard at harvest festivals, village celebrations and folk music stages.',
  'വിളവെടുപ്പ് ഉത്സവങ്ങളിലും ഗ്രാമാഘോഷങ്ങളിലും നാടൻപാട്ട് വേദികളിലും.']),
'sreebhoothabali': ('lamp', 'Thimila · Edakka · Chenda · Conch',
 ['A temple ritual of offerings around the sanctum, accompanied by temple drummers.',
  'ക്ഷേത്രവാദ്യക്കാരുടെ അകമ്പടിയോടെ ശ്രീകോവിലിനു ചുറ്റും ബലി തൂകുന്ന ചടങ്ങ്.'],
 ['Offerings are made to the bhoothaganas, the attendants of the deity, at the balikkallu stones around the temple.',
  'ദേവന്റെ പരിവാരങ്ങളായ ഭൂതഗണങ്ങൾക്ക് ക്ഷേത്രത്തിനു ചുറ്റുമുള്ള ബലിക്കല്ലുകളിൽ ബലി തൂകുന്നു.'],
 ['Performed daily in many temples and with special grandeur during festival days.',
  'പല ക്ഷേത്രങ്ങളിലും ദിവസേനയും ഉത്സവദിവസങ്ങളിൽ വിശേഷാലും.']),
'melappadam': ('chenda', 'Chenda · Maddalam · Chengila · Elathalam · Voice',
 ['The Kathakali prelude where singers and the chenda and maddalam players show their art before the play.',
  'കഥകളിക്കു മുമ്പ് പാട്ടുകാരും ചെണ്ട, മദ്ദളം വാദകരും കലാവൈഭവം പ്രദർശിപ്പിക്കുന്ന ആമുഖം.'],
 ['Melappadam is sung to a song from the Gita Govinda and gives the drummers a chance to shine on their own.',
  'ഗീതഗോവിന്ദത്തിലെ ഗാനം പാടുന്ന മേളപ്പദം വാദ്യക്കാർക്ക് സ്വന്തം മികവ് കാണിക്കാനുള്ള അവസരമാണ്.'],
 ['Performed at the start of a Kathakali night at temple festivals.',
  'ക്ഷേത്രോത്സവങ്ങളിലെ കഥകളിരാത്രിയുടെ തുടക്കത്തിൽ.']),
'thidambunritham': ('chenda', 'Chenda · Elathalam · Kombu',
 ['A temple dance in which the priest carries the deity’s replica on his head and dances to the chenda.',
  'ദേവന്റെ തിടമ്പ് തലയിലേന്തി പൂജാരി ചെണ്ടയുടെ താളത്തിൽ നൃത്തം ചെയ്യുന്ന ക്ഷേത്രകല.'],
 ['It is a tradition of north Malabar temples, performed by Namboothiri priests with careful footwork.',
  'ഉത്തരമലബാറിലെ ക്ഷേത്രങ്ങളിൽ നമ്പൂതിരിമാർ ചിട്ടയായ ചുവടുകളോടെ അവതരിപ്പിക്കുന്ന പാരമ്പര്യം.'],
 ['Performed during temple festivals when the deity is taken out in procession.',
  'ദേവനെ എഴുന്നള്ളിക്കുന്ന ഉത്സവദിവസങ്ങളിൽ.']),
'velakali': ('chenda', 'Chenda · Kombu · Elathalam',
 ['A martial dance with shields and swords, set to chenda and kombu.',
  'പരിചയും വാളുമേന്തി ചെണ്ടയുടെയും കൊമ്പിന്റെയും താളത്തിൽ ആടുന്ന ആയോധനനൃത്തം.'],
 ['Velakali recalls the warriors of old Kerala kingdoms, and its dancers wear colourful soldier costumes.',
  'പഴയ നാട്ടുരാജ്യങ്ങളിലെ യോദ്ധാക്കളെ ഓർമ്മിപ്പിക്കുന്ന വേലകളിയിൽ വർണ്ണാഭമായ പടയാളിവേഷം.'],
 ['Famous at the Ambalappuzha Sree Krishna temple festival and other temples of central Travancore.',
  'അമ്പലപ്പുഴ ശ്രീകൃഷ്ണക്ഷേത്രോത്സവത്തിലും മധ്യതിരുവിതാംകൂറിലെ മറ്റു ക്ഷേത്രങ്ങളിലും പ്രസിദ്ധം.']),
'kanyarkali': ('chenda', 'Chenda · Elathalam · Voice',
 ['A night-long folk dance of Palakkad villages, with songs and chenda.',
  'പാട്ടും ചെണ്ടയുമായി രാത്രി മുഴുവൻ നീളുന്ന പാലക്കാടൻ ഗ്രാമങ്ങളിലെ നാടൻനൃത്തം.'],
 ['Kanyarkali mixes devotional dance with comic sketches that show village life.',
  'ഭക്തിനൃത്തവും ഗ്രാമജീവിതം കാണിക്കുന്ന ഹാസ്യരംഗങ്ങളും ചേർന്നതാണ് കണ്യാർകളി.'],
 ['Performed in Bhagavathi temple grounds over several nights, around Vishu and the summer festival season.',
  'വിഷു, വേനൽ ഉത്സവകാലത്ത് ഭഗവതിക്ഷേത്രപ്പറമ്പുകളിൽ പല രാത്രികളിലായി.']),
'arjunanritham': ('chenda', 'Chenda · Elathalam · Voice',
 ['Dancers in skirts of peacock feathers spin and leap to chenda and songs.',
  'മയിൽപ്പീലിപ്പാവാട അണിഞ്ഞവർ ചെണ്ടയുടെയും പാട്ടിന്റെയും താളത്തിൽ കറങ്ങി ചാടുന്നു.'],
 ['Also called Mayilpeeli Thookkam, it is linked in legend to Arjuna dancing to please the goddess.',
  'മയിൽപ്പീലി തൂക്കം എന്നും പേര്; ദേവിയെ പ്രസാദിപ്പിക്കാൻ അർജുനൻ ആടിയെന്ന ഐതിഹ്യം.'],
 ['Performed at Bhagavathi temples of central Travancore during festival season.',
  'ഉത്സവകാലത്ത് മധ്യതിരുവിതാംകൂറിലെ ഭഗവതിക്ഷേത്രങ്ങളിൽ.']),
'poorakkali': ('dance', 'Voice · Hand claps',
 ['Men dance in a circle around a lamp, singing songs in praise of Kama.',
  'വിളക്കിനു ചുറ്റും പുരുഷന്മാർ കാമദേവ സ്തുതികൾ പാടി വട്ടത്തിൽ ആടുന്നു.'],
 ['Poorakkali is part of the Pooram festival of north Malabar, with complex steps learned over many years.',
  'ഉത്തരമലബാറിലെ പൂരോത്സവത്തിന്റെ ഭാഗം; വർഷങ്ങളെടുത്ത് പഠിക്കുന്ന സങ്കീർണ്ണ ചുവടുകൾ.'],
 ['Performed in temples during the Pooram festival in the month of Meenam.',
  'മീനമാസത്തിലെ പൂരോത്സവത്തിൽ ക്ഷേത്രങ്ങളിൽ.']),
'kolamthullal': ('mask', 'Chenda · Thappu · Voice',
 ['Dancers wearing masks made of areca palm sheaths perform to chenda and songs.',
  'കമുകിൻപാള കൊണ്ടുള്ള കോലങ്ങൾ അണിഞ്ഞ് ചെണ്ടയുടെയും പാട്ടിന്റെയും താളത്തിൽ തുള്ളുന്നു.'],
 ['Kolam Thullal is a healing ritual in which the masked figures are believed to drive away evil influences.',
  'ദുഷ്ടശക്തികളെ അകറ്റുമെന്ന് വിശ്വസിക്കപ്പെടുന്ന ചികിത്സാ അനുഷ്ഠാനമാണ് കോലംതുള്ളൽ.'],
 ['Held at homes and village temples in south Kerala.',
  'തെക്കൻ കേരളത്തിലെ വീടുകളിലും ഗ്രാമക്ഷേത്രങ്ങളിലും.']),
'sarpamthullal': ('lamp', 'Pulluvan veena · Kudam · Voice',
 ['A serpent ritual where women sway to Pulluvan songs beside a kalam of serpents.',
  'സർപ്പക്കളത്തിനരികെ പുള്ളുവൻ പാട്ടിന്റെ താളത്തിൽ സ്ത്രീകൾ തുള്ളുന്ന ചടങ്ങ്.'],
 ['As the songs build, the women sway into a trance and sweep away the serpent kalam with their hair.',
  'പാട്ട് മുറുകുമ്പോൾ സ്ത്രീകൾ ഉറഞ്ഞുതുള്ളി മുടികൊണ്ട് സർപ്പക്കളം മായ്ക്കുന്നു.'],
 ['Held at family serpent groves and homes to bring blessings.',
  'ഐശ്വര്യത്തിനായി തറവാട് സർപ്പക്കാവുകളിലും വീടുകളിലും.']),
'theeyattu': ('lamp', 'Chenda · Elathalam · Voice',
 ['A ritual with a floor drawing, songs and percussion, ending in a dance with fire.',
  'കളമെഴുത്തും പാട്ടും വാദ്യവുമായി, തീയോടെയുള്ള നൃത്തത്തിൽ അവസാനിക്കുന്ന അനുഷ്ഠാനം.'],
 ['Performed by the Theeyattunni community for Ayyappan or Bhadrakali.',
  'തീയാട്ടുണ്ണി സമുദായക്കാർ അയ്യപ്പനോ ഭദ്രകാളിക്കോ വേണ്ടി നടത്തുന്നു.'],
 ['Held in temples and homes as an offering for blessings.',
  'അനുഗ്രഹത്തിനായി ക്ഷേത്രങ്ങളിലും വീടുകളിലും വഴിപാടായി.']),
'marappani': ('hand', 'Maram · Valampiri shankh · Elathalam',
 ['A rare temple percussion played on the maram, a large wooden drum, with the valampiri shankh and elathalam.', 'വലിയ മരവാദ്യമായ മരത്തിൽ, വലംപിരി ശംഖും ഇലത്താളവും ചേർത്ത് കൊട്ടുന്ന അപൂർവ ക്ഷേത്രവാദ്യം.'],
 ['Marar temple musicians play it at consecrations such as Navakam and Sahasrakalasam, when sacred pots of water are offered to the deity. Its rhythms follow strict temple rules.', 'നവകം, സഹസ്രകലശം തുടങ്ങിയ ചടങ്ങുകളിൽ കലശം അഭിഷേകം ചെയ്യുമ്പോൾ മാരാർ വാദ്യകലാകാരന്മാർ കൊട്ടുന്നു. കർശനമായ ക്ഷേത്രനിയമങ്ങൾ പാലിച്ചാണ് ഇതിന്റെ താളം.'],
 ['Heard inside the temple during kalasam and purification rites of the annual festival, not in processions.', 'ഉത്സവകാലത്തെ കലശ-ശുദ്ധിക്രിയകളിൽ ക്ഷേത്രത്തിനുള്ളിൽ; എഴുന്നള്ളിപ്പുകളിൽ ഇല്ല.']),
'tholpavakoothu': ('lamp', 'Ezhupara · Chenda · Maddalam · Elathalam · Shankh',
 ['Leather shadow puppets act out the Kamba Ramayanam behind a lamp-lit screen, to chanting and percussion.', 'വിളക്കു കത്തിച്ച തിരശ്ശീലയ്ക്കു പിന്നിൽ തുകൽപ്പാവകൾ കമ്പരാമായണം പാട്ടിന്റെയും വാദ്യത്തിന്റെയും താളത്തിൽ അവതരിപ്പിക്കുന്നു.'],
 ['Pulavar families of Palakkad have kept the art alive for generations. A full performance can run for many nights, one episode each night, in a temple theatre called the koothumadam.', 'പാലക്കാട്ടെ പുലവർ കുടുംബങ്ങൾ തലമുറകളായി ഈ കല നിലനിർത്തുന്നു. കൂത്തുമാടം എന്ന ക്ഷേത്രവേദിയിൽ ഓരോ രാത്രിയും ഓരോ ഭാഗമായി പല രാത്രികൾ നീളും.'],
 ['Staged in Bhagavathi temples of Palakkad and Thrissur during the festival season, roughly January to May.', 'ഉത്സവകാലത്ത് (ഏകദേശം ജനുവരി മുതൽ മേയ് വരെ) പാലക്കാട്, തൃശ്ശൂർ ഭഗവതിക്ഷേത്രങ്ങളിൽ.']),
'kaliyoottu': ('mask', 'Chenda · Elathalam · Kuzhal · Voice',
 ["A long ritual of Bhadrakali's battle with the demon Darika, told through songs, drums and dramatic scenes.", 'ഭദ്രകാളിയും ദാരികനും തമ്മിലുള്ള യുദ്ധം പാട്ടും വാദ്യവും രംഗങ്ങളുമായി അവതരിപ്പിക്കുന്ന നീണ്ട അനുഷ്ഠാനം.'],
 ['At Sarkara Devi temple near Chirayinkeezhu it unfolds over several nights and ends with the slaying of Darika.', 'ചിറയിൻകീഴിനടുത്തുള്ള ശാർക്കര ദേവീക്ഷേത്രത്തിൽ പല രാത്രികളിലായി നടന്ന് ദാരികവധത്തോടെ സമാപിക്കുന്നു.'],
 ['Held at the Sarkara Kaliyoottu festival and in other Bhadrakali temples of south Kerala.', 'ശാർക്കര കാളിയൂട്ട് മഹോത്സവത്തിലും തെക്കൻ കേരളത്തിലെ മറ്റ് ഭദ്രകാളിക്ഷേത്രങ്ങളിലും.']),
'kuthiyottam': ('dance', 'Chenda · Elathalam · Voice',
 ['Boys who have taken a vow dance in a group to songs and percussion as an offering to Bhagavathi.', 'നേർച്ചയെടുത്ത ബാലന്മാർ സംഘമായി പാട്ടിന്റെയും വാദ്യത്തിന്റെയും താളത്തിൽ ഭഗവതിക്കു മുന്നിൽ ചുവടുവയ്ക്കുന്നു.'],
 ['It belongs to the Onattukara region. Families who make the vow host the boys and the singers for days of practice before the festival.', 'ഓണാട്ടുകരയുടെ സ്വന്തം അനുഷ്ഠാനം. നേർച്ചയെടുത്ത വീട്ടുകാർ ഉത്സവത്തിനു മുമ്പ് ദിവസങ്ങളോളം ബാലന്മാരെയും പാട്ടുകാരെയും സ്വീകരിച്ച് പരിശീലിപ്പിക്കുന്നു.'],
 ['Best known at the Kumbha Bharani festival of Chettikulangara Bhagavathi temple.', 'ചെട്ടികുളങ്ങര ഭഗവതിക്ഷേത്രത്തിലെ കുംഭഭരണിക്കാണ് ഏറ്റവും പ്രസിദ്ധം.']),
'poothankali': ('mask', 'Chenda · Thudi · Elathalam',
 ['Poothan, in a bright crown and mask with jingling bells, dances from house to house with drummers.', 'തിളങ്ങുന്ന കിരീടവും മുഖംമൂടിയും ചിലമ്പുമണിഞ്ഞ പൂതൻ വാദ്യക്കാരോടൊപ്പം വീടുതോറും ആടുന്നു.'],
 ['Poothan and Thira are said to be attendants of Kali. They visit families before the festival to bless them.', 'പൂതനും തിറയും കാളിയുടെ ഭൂതഗണങ്ങളാണെന്നാണ് വിശ്വാസം. ഉത്സവത്തിനു മുമ്പ് വീടുകളിലെത്തി അനുഗ്രഹിക്കുന്നു.'],
 ['Seen at the Pooram and Vela festivals of Bhagavathi temples in Palakkad and Malappuram.', 'പാലക്കാട്, മലപ്പുറം ഭഗവതിക്ഷേത്രങ്ങളിലെ പൂരം, വേല ഉത്സവങ്ങളിൽ.']),
'paana': ('lamp', 'Chenda · Elathalam · Kuzhal · Voice',
 ['A night-long Bhadrakali ritual with Paana songs, lamps and drums under a pandal decorated with palm leaves.', 'കുരുത്തോല അലങ്കരിച്ച പന്തലിൽ പാനപ്പാട്ടും വിളക്കും വാദ്യവുമായി രാത്രി മുഴുവൻ നീളുന്ന ഭദ്രകാളി അനുഷ്ഠാനം.'],
 ['Families offer Paana for prosperity. As the songs reach their peak, the velichappadu dances in trance.', 'ഐശ്വര്യത്തിനായി കുടുംബങ്ങൾ പാന നേരുന്നു. പാട്ട് മുറുകുമ്പോൾ വെളിച്ചപ്പാട് ഉറഞ്ഞുതുള്ളുന്നു.'],
 ['Held in Valluvanad homes and Bhagavathi temples, often ahead of the temple festival.', 'വള്ളുവനാട്ടിലെ വീടുകളിലും ഭഗവതിക്ഷേത്രങ്ങളിലും, പലപ്പോഴും ഉത്സവത്തിനു മുന്നോടിയായി.']),
'kothamooriyattam': ('dance', 'Chenda · Elathalam · Voice',
 ['A cow-headed figure, the Kothamoori, goes from house to house with dancers, songs and drums.', 'പശുവിന്റെ തലയുള്ള കോതാമൂരി, നർത്തകരോടും പാട്ടിനോടും വാദ്യത്തോടും കൂടി വീടുതോറും എത്തുന്നു.'],
 ['It is performed in north Malabar by the Malaya community and is said to bring blessings to cattle and crops.', 'ഉത്തരമലബാറിൽ മലയ സമുദായക്കാർ അവതരിപ്പിക്കുന്നു; കന്നുകാലികൾക്കും വിളകൾക്കും ഐശ്വര്യം നൽകുമെന്നാണ് വിശ്വാസം.'],
 ['Seen in Kannur and Kasaragod villages in the harvest season.', 'വിളവെടുപ്പുകാലത്ത് കണ്ണൂർ, കാസർകോട് ഗ്രാമങ്ങളിൽ.']),
'kavadiyattam': ('pipe', 'Nadaswaram · Thakil · Udukku · Chenda',
 ['Devotees dance carrying decorated kavadi arches on their shoulders, to nadaswaram, thakil and udukku.', 'അലങ്കരിച്ച കാവടികൾ തോളിലേന്തി ഭക്തർ നാദസ്വരം, തകിൽ, ഉടുക്ക് എന്നിവയുടെ താളത്തിൽ ആടുന്നു.'],
 ['It is an offering to Lord Subrahmanya. Dancers often keep a fast for days before carrying the kavadi.', 'സുബ്രഹ്മണ്യസ്വാമിക്കുള്ള വഴിപാട്. കാവടിയെടുക്കുന്നവർ ദിവസങ്ങളോളം വ്രതമെടുക്കുന്നു.'],
 ['The highlight of Thaipooyam at Haripad, Koorkenchery and other Subrahmanya temples.', 'ഹരിപ്പാട്, കൂർക്കഞ്ചേരി തുടങ്ങിയ സുബ്രഹ്മണ്യക്ഷേത്രങ്ങളിലെ തൈപ്പൂയത്തിന്റെ പ്രധാന ആകർഷണം.']),
'thalappoli': ('lamp', 'Chenda · Elathalam · Kombu · Kuzhal',
 ['Women and girls walk in procession carrying lit lamps on brass plates with rice and flowers.', 'അരിയും പൂവും വിളക്കും വച്ച പിച്ചളത്താലങ്ങളേന്തി സ്ത്രീകളും പെൺകുട്ടികളും ഘോഷയാത്രയായി നീങ്ങുന്നു.'],
 ['The lamps welcome the deity. The procession moves slowly, set to the melam playing at its head.', 'വിളക്കുകൾ ദേവിയെ വരവേൽക്കുന്നു. മുന്നിലെ മേളത്തിന്റെ താളത്തിൽ ഘോഷയാത്ര പതുക്കെ നീങ്ങുന്നു.'],
 ['A feature of Bhagavathi temple festivals across central Kerala, usually at dusk.', 'മധ്യകേരളത്തിലെ ഭഗവതിക്ഷേത്രോത്സവങ്ങളിൽ, സാധാരണയായി സന്ധ്യയ്ക്ക്.']),
'brahmanipattu': ('sticks', 'Elathalam · Voice',
 ['Women of the Brahmani community sing devotional songs, keeping time on the elathalam.', 'ബ്രാഹ്മണി സമുദായത്തിലെ സ്ത്രീകൾ ഇലത്താളത്തിൽ താളം പിടിച്ച് ഭക്തിഗാനങ്ങൾ പാടുന്നു.'],
 ['The songs are sung inside Bhadrakali and Durga temples as part of the rituals, and the words are passed down within families.', 'ഭദ്രകാളി, ദുർഗ ക്ഷേത്രങ്ങളിൽ ചടങ്ങുകളുടെ ഭാഗമായി പാടുന്നു; പാട്ടുകൾ കുടുംബങ്ങളിൽ തലമുറകളായി കൈമാറുന്നു.'],
 ['Offered during temple festivals and special poojas in central Kerala.', 'മധ്യകേരളത്തിലെ ഉത്സവങ്ങളിലും വിശേഷാൽ പൂജകളിലും വഴിപാടായി.']),
'thottampattu': ('chenda', 'Chenda · Elathalam · Voice',
 ['Invocation songs that call the deity into the Theyyam performer, sung to chenda and elathalam.', 'തെയ്യക്കാരനിലേക്ക് ദേവതയെ ആവാഹിക്കുന്ന സ്തുതിപ്പാട്ടുകൾ, ചെണ്ടയും ഇലത്താളവും അകമ്പടി.'],
 ["The thottam tells the story of the deity. As it builds, the performer begins to take on the deity's form.", 'തോറ്റം ദേവതയുടെ കഥ പറയുന്നു. പാട്ട് മുറുകുംതോറും കോലധാരി ദേവതയായി മാറുന്നു.'],
 ['Sung in the kavus of Kannur and Kasaragod on the eve of Theyyam, through the Theyyam season.', 'തെയ്യക്കാലത്ത് കണ്ണൂർ, കാസർകോട് കാവുകളിൽ തെയ്യത്തിന്റെ തലേന്ന്.']),
'gaddika': ('pipe', 'Thudi · Chenda · Kuzhal · Voice',
 ['A healing ritual of Wayanad with songs, dance and the beat of thudi drums and kuzhal.', 'പാട്ടും നൃത്തവും തുടിയും കുഴലുമായി വയനാട്ടിലെ രോഗശാന്തി അനുഷ്ഠാനം.'],
 ['Performed by the Adiya community to drive away illness and bring good fortune to a home or village.', 'രോഗം അകറ്റാനും വീടിനും ഊരിനും ഐശ്വര്യം വരുത്താനും അടിയ സമുദായക്കാർ നടത്തുന്നു.'],
 ['Held in Wayanad settlements and around the Valliyoorkavu festival.', 'വയനാട്ടിലെ ഊരുകളിലും വള്ളിയൂർക്കാവ് ഉത്സവകാലത്തും.']),
'koodiyattam': ('hand', 'Mizhavu · Kuzhithalam · Edakka · Kombu · Shankh',
 ['The oldest living Sanskrit theatre in the world, performed by Chakyars and Nangiars to the deep beat of the mizhavu.', 'ചാക്യാരും നങ്ങ്യാരും മിഴാവിന്റെ താളത്തിൽ അവതരിപ്പിക്കുന്ന, ലോകത്ത് ഇന്നും ജീവിക്കുന്ന ഏറ്റവും പഴയ സംസ്കൃത നാടകം.'],
 ['It has been performed in Kerala temples for around two thousand years, and UNESCO recognised it in 2001. A single act can take many nights.', 'ഏകദേശം രണ്ടായിരം വർഷമായി കേരളത്തിലെ ക്ഷേത്രങ്ങളിൽ അവതരിപ്പിക്കുന്നു; 2001-ൽ യുനെസ്കോ അംഗീകരിച്ചു. ഒരു അങ്കം തന്നെ പല രാത്രികൾ നീളാം.'],
 ['Staged in the koothambalam, the temple theatre, as an offering during temple festivals.', 'ഉത്സവകാലത്ത് വഴിപാടായി ക്ഷേത്രത്തിലെ കൂത്തമ്പലത്തിൽ.']),
'nangiarkoothu': ('hand', 'Mizhavu · Kuzhithalam · Edakka',
 ['A solo performance by Nangiar women, born from Koodiyattam, telling the story of Krishna through gesture and expression.', 'കൂടിയാട്ടത്തിൽ നിന്ന് ഉരുത്തിരിഞ്ഞ നങ്ങ്യാരുടെ ഏകാംഗ അവതരണം; മുദ്രയും ഭാവവും കൊണ്ട് കൃഷ്ണകഥ പറയുന്നു.'],
 ['It was revived in the late 20th century from old acting manuals called attaprakaram.', 'ആട്ടപ്രകാരം എന്ന പഴയ അഭിനയഗ്രന്ഥങ്ങളിൽ നിന്ന് ഇരുപതാം നൂറ്റാണ്ടിന്റെ അവസാനം പുനരുജ്ജീവിപ്പിച്ചു.'],
 ['Performed in koothambalams and on classical arts stages.', 'കൂത്തമ്പലങ്ങളിലും ക്ലാസിക്കൽ കലാവേദികളിലും.']),
'pathakam': ('hand', 'Mizhavu · Voice',
 ['A story-telling art in which a Nambiar narrates the Puranas in Sanskrit and Malayalam, accompanied by the mizhavu.', 'നമ്പ്യാർ സംസ്കൃതത്തിലും മലയാളത്തിലും പുരാണകഥകൾ പറയുന്ന കല; മിഴാവ് അകമ്പടി.'],
 ["It belongs to the same temple tradition as Chakyar Koothu, but is told more simply, without the Chakyar's costume.", 'ചാക്യാർകൂത്തിന്റെ അതേ ക്ഷേത്രപാരമ്പര്യത്തിൽ പെടുന്നു, പക്ഷേ ചാക്യാരുടെ വേഷമില്ലാതെ ലളിതമായി പറയുന്നു.'],
 ['Heard in temple halls during the festival season.', 'ഉത്സവകാലത്ത് ക്ഷേത്ര മണ്ഡപങ്ങളിൽ.']),
'ramanattam': ('mask', 'Chenda · Maddalam · Chengila · Elathalam · Voice',
 ['The Ramayana told as dance-drama, created in the 17th century by the Raja of Kottarakkara.', 'പതിനേഴാം നൂറ്റാണ്ടിൽ കൊട്ടാരക്കര തമ്പുരാൻ രൂപപ്പെടുത്തിയ രാമായണ നൃത്തനാടകം.'],
 ['It grew into Kathakali, and Kottarakkara is still remembered as the birthplace of the art.', 'ഇത് കഥകളിയായി വളർന്നു; കൊട്ടാരക്കര ഇന്നും കഥകളിയുടെ ജന്മനാടായി അറിയപ്പെടുന്നു.'],
 ['Its stories are performed today as Kathakali in temples through the night.', 'ഇന്ന് ഈ കഥകൾ ക്ഷേത്രങ്ങളിൽ രാത്രി മുഴുവൻ കഥകളിയായി അവതരിപ്പിക്കുന്നു.']),
'sanghakali': ('sticks', 'Voice · Hand claps · Sticks',
 ['An old performance of the Nambudiri community that mixes songs, martial movements and comic scenes.', 'പാട്ടും ആയോധനച്ചുവടുകളും ഹാസ്യരംഗങ്ങളും ചേർന്ന നമ്പൂതിരി സമുദായത്തിന്റെ പഴയ കല.'],
 ['Also called Chathirankali or Yathrakali, it is linked to the warrior groups of old Kerala.', 'ചാത്തിരങ്കളി, യാത്രക്കളി എന്നും പേരുണ്ട്; പഴയ കേരളത്തിലെ യോദ്ധാക്കളുടെ സംഘങ്ങളുമായി ബന്ധപ്പെട്ടത്.'],
 ['Performed at homes and temples for weddings and festivals.', 'വിവാഹങ്ങൾക്കും ഉത്സവങ്ങൾക്കും വീടുകളിലും ക്ഷേത്രങ്ങളിലും.']),
'seethankanthullal': ('dance', 'Maddalam · Elathalam · Voice',
 ['One of the three Thullal forms created by Kunchan Nambiar in the 18th century, sung in a gentle rhythm.', 'പതിനെട്ടാം നൂറ്റാണ്ടിൽ കുഞ്ചൻ നമ്പ്യാർ രൂപപ്പെടുത്തിയ മൂന്നു തുള്ളലുകളിലൊന്ന്, മൃദുതാളത്തിൽ.'],
 ['The dancer wears tender palm leaves and tells comic stories in simple Malayalam.', 'കുരുത്തോല അണിഞ്ഞ് ലളിതമായ മലയാളത്തിൽ ഹാസ്യകഥകൾ പറയുന്നു.'],
 ['Performed in temple yards and on festival stages.', 'ക്ഷേത്രമുറ്റങ്ങളിലും ഉത്സവവേദികളിലും.']),
'parayanthullal': ('dance', 'Maddalam · Elathalam · Voice',
 ['The slowest of the three Thullal forms of Kunchan Nambiar, recited while the performer stands more than dances.', 'കുഞ്ചൻ നമ്പ്യാരുടെ മൂന്നു തുള്ളലുകളിൽ ഏറ്റവും പതിഞ്ഞത്; നൃത്തത്തേക്കാൾ നിന്നുള്ള ചൊല്ലൽ.'],
 ['Its verses are recited in a slow rhythm, and its costume is the simplest of the three.', 'പതിഞ്ഞ താളത്തിൽ വരികൾ ചൊല്ലുന്നു; മൂന്നിൽ ഏറ്റവും ലളിതമായ വേഷം.'],
 ['Performed in temple yards and on festival stages.', 'ക്ഷേത്രമുറ്റങ്ങളിലും ഉത്സവവേദികളിലും.']),
'pavakathakali': ('mask', 'Chenda · Chengila · Elathalam · Shankh · Voice',
 ['Glove-puppet Kathakali, where small wooden puppets in full Kathakali costume act the stories.', 'കഥകളി വേഷമണിഞ്ഞ ചെറിയ മരപ്പാവകൾ കഥകൾ അഭിനയിക്കുന്ന കൈപ്പാവകളി.'],
 ['It came to Kerala with families from Andhra who settled near Palakkad, and is kept alive at Paruthipully.', 'ആന്ധ്രയിൽ നിന്ന് പാലക്കാടിനടുത്ത് താമസമാക്കിയ കുടുംബങ്ങളോടൊപ്പം എത്തി; പരുത്തിപ്പുള്ളിയിൽ ഇന്നും നിലനിൽക്കുന്നു.'],
 ['Performed at temple festivals and cultural shows.', 'ക്ഷേത്രോത്സവങ്ങളിലും സാംസ്കാരിക പരിപാടികളിലും.']),
'parichamuttukali': ('sticks', 'Swords · Shields · Voice · Hand claps',
 ['A martial dance of Saint Thomas Christians with sword and shield, to songs and the clash of weapons.', 'വാളും പരിചയുമായി പാട്ടിന്റെയും ആയുധങ്ങളുടെ മുട്ടലിന്റെയും താളത്തിൽ ക്രൈസ്തവരുടെ ആയോധന നൃത്തം.'],
 ['It draws on Kalaripayattu and was once a display of warrior skill.', 'കളരിപ്പയറ്റിൽ നിന്ന് ഉരുത്തിരിഞ്ഞത്; ഒരുകാലത്ത് യോദ്ധാക്കളുടെ മികവിന്റെ പ്രദർശനം.'],
 ['Performed at church feasts in central Kerala.', 'മധ്യകേരളത്തിലെ പള്ളിപ്പെരുന്നാളുകളിൽ.']),
'kurathiyattam': ('dance', 'Chenda · Maddalam · Elathalam · Voice',
 ['A folk dance-drama of the Kurathi, the fortune teller, with lively songs and comic dialogue.', 'ഭാവി പറയുന്ന കുറത്തിയുടെ ചടുലമായ പാട്ടും ഹാസ്യസംഭാഷണവുമുള്ള നാടൻ നൃത്തനാടകം.'],
 ['It often tells stories of Shiva and Parvathi in the guise of the Kuravan and Kurathi.', 'കുറവന്റെയും കുറത്തിയുടെയും വേഷത്തിൽ പലപ്പോഴും ശിവ-പാർവതി കഥകൾ പറയുന്നു.'],
 ['Seen at temple festivals in central and south Kerala.', 'മധ്യ-തെക്കൻ കേരളത്തിലെ ക്ഷേത്രോത്സവങ്ങളിൽ.']),
'thuyilunarthu': ('edakka', 'Thudi · Voice',
 ['Dawn songs sung by the Pana community going from house to house with the thudi drum to wake people.', 'തുടി കൊട്ടി വീടുതോറും നടന്ന് ആളുകളെ ഉണർത്തുന്ന പാണ സമുദായത്തിന്റെ പുലർകാല പാട്ടുകൾ.'],
 ['During Onam they sing to wake Mahabali and the household, and receive rice and gifts.', 'ഓണക്കാലത്ത് മഹാബലിയെയും വീട്ടുകാരെയും ഉണർത്താൻ പാടി അരിയും സമ്മാനങ്ങളും വാങ്ങുന്നു.'],
 ['Heard in the early mornings of Onam in villages.', 'ഓണക്കാലത്തെ പുലരികളിൽ ഗ്രാമങ്ങളിൽ.']),
'bandmelam': ('horn', 'Trumpet · Clarinet · Euphonium · Side drum · Bass drum · Cymbals',
 ['Uniformed brass bands play marches, hymns and film songs at church feasts, temple processions and weddings.', 'യൂണിഫോമിട്ട ബ്രാസ് ബാൻഡുകൾ പള്ളിപ്പെരുന്നാളുകളിലും ക്ഷേത്ര ഘോഷയാത്രകളിലും വിവാഹങ്ങളിലും മാർച്ചുകളും ഭക്തിഗാനങ്ങളും സിനിമാഗാനങ്ങളും വായിക്കുന്നു.'],
 ['Brass bands came to Kerala with military and church bands in colonial times and became part of village festivals.', 'കൊളോണിയൽ കാലത്ത് സൈനിക-പള്ളി ബാൻഡുകളിലൂടെ കേരളത്തിലെത്തി ഗ്രാമോത്സവങ്ങളുടെ ഭാഗമായി.'],
 ['Heard at church perunnals, temple processions and weddings, often alongside the chenda melam.', 'പള്ളിപ്പെരുന്നാളുകളിലും ക്ഷേത്ര ഘോഷയാത്രകളിലും വിവാഹങ്ങളിലും, പലപ്പോഴും ചെണ്ടമേളത്തോടൊപ്പം.']),
'thappukottu': ('hand', 'Thappu · Voice',
 ['Loud, fast rhythms played on the thappu, a flat frame drum heated over fire to tighten its skin.', 'തീയിൽ ചൂടാക്കി തോൽ മുറുക്കിയ പരന്ന തപ്പിൽ കൊട്ടുന്ന ഉച്ചത്തിലുള്ള ദ്രുതതാളം.'],
 ['It belongs to the Dalit communities of Kerala and is now proudly played on folk arts stages.', 'കേരളത്തിലെ ദളിത് സമുദായങ്ങളുടെ കല; ഇന്ന് നാടൻകലാവേദികളിൽ അഭിമാനത്തോടെ അവതരിപ്പിക്കുന്നു.'],
 ['Heard at temple festivals, processions and folk festivals.', 'ക്ഷേത്രോത്സവങ്ങളിലും ഘോഷയാത്രകളിലും നാടൻകലോത്സവങ്ങളിലും.']),
'malayankettu': ('mask', 'Chenda · Elathalam · Voice',
 ['A healing ritual of the Malayan community in north Malabar, with masked figures, songs and drums.', 'മുഖംമൂടിയണിഞ്ഞ രൂപങ്ങളും പാട്ടും വാദ്യവുമായി ഉത്തരമലബാറിലെ മലയ സമുദായത്തിന്റെ രോഗശാന്തി അനുഷ്ഠാനം.'],
 ['It is performed to drive away illness and bad influences from a home.', 'വീട്ടിൽ നിന്ന് രോഗവും ദോഷവും അകറ്റാൻ നടത്തുന്നു.'],
 ['Held in homes in Kannur and Kasaragod.', 'കണ്ണൂരിലെയും കാസർകോട്ടെയും വീടുകളിൽ.']),
'mangalamkali': ('dance', 'Thudi · Voice',
 ['A wedding dance of the Mavilan and Malavettuvan communities of Kasaragod, danced in a circle to the thudi.', 'കാസർകോട്ടെ മാവിലൻ, മലവേട്ടുവൻ സമുദായങ്ങൾ തുടിയുടെ താളത്തിൽ വട്ടത്തിൽ ആടുന്ന വിവാഹനൃത്തം.'],
 ['Men and women sing and dance around a lamp through the wedding night.', 'വിവാഹരാത്രി മുഴുവൻ വിളക്കിനു ചുറ്റും സ്ത്രീകളും പുരുഷന്മാരും പാടി ആടുന്നു.'],
 ['Seen at weddings and folk festivals in Kasaragod.', 'കാസർകോട്ടെ വിവാഹങ്ങളിലും നാടൻകലോത്സവങ്ങളിലും.']),
'velichappadu': ('dance', 'Chenda · Elathalam · Chilambu',
 ['The temple oracle, in red with anklets and a curved sword, dances in trance as the drums speed up.', 'ചുവപ്പുടുത്ത് ചിലമ്പും പള്ളിവാളുമേന്തിയ വെളിച്ചപ്പാട് വാദ്യം മുറുകുമ്പോൾ ഉറഞ്ഞുതുള്ളുന്നു.'],
 ['The velichappadu is believed to speak for the goddess during the festival.', 'ഉത്സവസമയത്ത് വെളിച്ചപ്പാട് ദേവിയുടെ വാക്കുകൾ പറയുന്നുവെന്നാണ് വിശ്വാസം.'],
 ['Seen at Bhagavathi temple festivals, especially Kodungallur Bharani.', 'ഭഗവതിക്ഷേത്രോത്സവങ്ങളിൽ, പ്രത്യേകിച്ച് കൊടുങ്ങല്ലൂർ ഭരണിക്ക്.']),
'ammankudam': ('pipe', 'Nadaswaram · Thavil · Udukku',
 ['Dancers carry decorated pots on their heads in honour of the mother goddess, to nadaswaram and thavil.', 'അമ്മദൈവത്തിനായി അലങ്കരിച്ച കുടങ്ങൾ തലയിലേന്തി നാദസ്വരത്തിന്റെയും തവിലിന്റെയും താളത്തിൽ ആടുന്നു.'],
 ['It came from Tamil traditions into the temples of southern Kerala.', 'തമിഴ് പാരമ്പര്യത്തിൽ നിന്ന് തെക്കൻ കേരളത്തിലെ ക്ഷേത്രങ്ങളിലെത്തി.'],
 ['Seen at temple festivals in Thiruvananthapuram and Kollam.', 'തിരുവനന്തപുരം, കൊല്ലം ക്ഷേത്രോത്സവങ്ങളിൽ.']),
'chimmanakali': ('dance', 'Chenda · Elathalam · Voice',
 ['A comic folk drama of north Kerala, with songs and dances that poke fun at daily life.', 'ദൈനംദിന ജീവിതത്തെ കളിയാക്കുന്ന പാട്ടും ആട്ടവുമുള്ള ഉത്തരകേരളത്തിലെ ഹാസ്യ നാടൻനാടകം.'],
 ['It is kept alive by the Pulaya community of north Malabar and mixes song, dance and satire.', 'ഉത്തരമലബാറിലെ പുലയ സമുദായം നിലനിർത്തുന്നു; പാട്ടും ആട്ടവും ആക്ഷേപഹാസ്യവും ചേർന്നത്.'],
 ['Seen at folk festivals and village celebrations.', 'നാടൻകലോത്സവങ്ങളിലും ഗ്രാമാഘോഷങ്ങളിലും.']),
'mappilapattu': ('hand', 'Voice · Harmonium · Tabla · Daf',
 ["Songs of Kerala's Muslim community, in Malayalam mixed with Arabic, Tamil and Persian words.", 'അറബി, തമിഴ്, പേർഷ്യൻ വാക്കുകൾ കലർന്ന മലയാളത്തിലുള്ള കേരള മുസ്ലിംകളുടെ പാട്ടുകൾ.'],
 ['Moyinkutty Vaidyar, born in 1852, is remembered as its greatest poet.', '1852-ൽ ജനിച്ച മോയിൻകുട്ടി വൈദ്യരാണ് ഇതിന്റെ ഏറ്റവും പ്രശസ്തനായ കവി.'],
 ['Sung at weddings, festivals and on stage across Malabar.', 'മലബാറിലെങ്ങും വിവാഹങ്ങളിലും ആഘോഷങ്ങളിലും വേദികളിലും.']),
'vattappattu': ('hand', 'Voice · Hand claps',
 ['Men sit in a circle, singing and clapping in praise of the bridegroom at a Mappila wedding.', 'മാപ്പിള വിവാഹത്തിൽ മണവാളനെ പുകഴ്ത്തി പുരുഷന്മാർ വട്ടത്തിലിരുന്ന് പാടി കൈകൊട്ടുന്നു.'],
 ['Its songs are sung on the night before the wedding and build up to fast clapping.', 'വിവാഹത്തലേന്ന് രാത്രി പാടുന്നു; പാട്ട് മുറുകുമ്പോൾ കൈകൊട്ടും വേഗത്തിലാകും.'],
 ['Heard at weddings and school arts festivals in Malabar.', 'മലബാറിലെ വിവാഹങ്ങളിലും സ്കൂൾ കലോത്സവങ്ങളിലും.']),
'kakkarissi': ('mask', 'Chenda · Maddalam · Elathalam · Voice',
 ['A folk musical play about Kakkan and Kakkathi, a wandering couple, full of songs and satire.', 'നാടോടി ദമ്പതികളായ കാക്കന്റെയും കാക്കാത്തിയുടെയും കഥ പറയുന്ന, പാട്ടും ആക്ഷേപഹാസ്യവും നിറഞ്ഞ നാടൻ സംഗീതനാടകം.'],
 ['Its story tells of Shiva and Parvathi coming to earth as the wandering couple.', 'ശിവനും പാർവതിയും നാടോടി ദമ്പതികളായി ഭൂമിയിലെത്തുന്നതാണ് കഥ.'],
 ['Staged at temple festivals in central and south Kerala.', 'മധ്യ-തെക്കൻ കേരളത്തിലെ ക്ഷേത്രോത്സവങ്ങളിൽ.']),
'porattu': ('mask', 'Chenda · Harmonium · Voice',
 ['A folk drama of Palakkad, with comic characters, songs and quick dialogue about village life.', 'ഹാസ്യകഥാപാത്രങ്ങളും പാട്ടും ഗ്രാമജീവിതത്തെക്കുറിച്ചുള്ള ചടുലസംഭാഷണവുമുള്ള പാലക്കാട്ടെ നാടൻനാടകം.'],
 ['Travelling troupes perform it, carrying sharp satire on society with plenty of humour.', 'സഞ്ചരിക്കുന്ന സംഘങ്ങൾ അവതരിപ്പിക്കുന്നു; നർമ്മത്തോടെ സമൂഹത്തെ വിമർശിക്കുന്നു.'],
 ['Seen at temple festivals in Palakkad, especially in the Vela season.', 'പാലക്കാട്ടെ ക്ഷേത്രോത്സവങ്ങളിൽ, പ്രത്യേകിച്ച് വേലക്കാലത്ത്.']),
'mohiniyattam': ('dance', 'Voice · Mridangam · Edakka · Flute · Veena',
 ["Kerala's graceful classical dance, with gentle swaying movements, sung in the sopana style.", 'സോപാനശൈലിയിലെ പാട്ടിനൊത്ത് മൃദുവായി ആടിയുലയുന്ന കേരളത്തിന്റെ ലാസ്യപ്രധാനമായ ക്ലാസിക്കൽ നൃത്തം.'],
 ['It took shape at the court of Swathi Thirunal in the 19th century and was revived at Kerala Kalamandalam.', 'പത്തൊമ്പതാം നൂറ്റാണ്ടിൽ സ്വാതി തിരുനാളിന്റെ സദസ്സിൽ രൂപം പ്രാപിച്ചു; കേരള കലാമണ്ഡലം പുനരുജ്ജീവിപ്പിച്ചു.'],
 ['Performed at temple festivals, Navarathri and classical arts stages.', 'ക്ഷേത്രോത്സവങ്ങളിലും നവരാത്രിക്കും ക്ലാസിക്കൽ കലാവേദികളിലും.']),
'kathakalipadam': ('mask', 'Voice · Chengila · Elathalam · Chenda · Maddalam',
 ['The sung part of Kathakali, where two singers lead with chengila and elathalam.', 'ചേങ്ങിലയും ഇലത്താളവുമായി രണ്ടു ഗായകർ നയിക്കുന്ന കഥകളിയുടെ സംഗീതഭാഗം.'],
 ['Padams are sung in ragas of the sopana style and are also performed on their own in concerts.', 'സോപാനശൈലിയിലെ രാഗങ്ങളിൽ പാടുന്ന പദങ്ങൾ കച്ചേരികളായി സ്വതന്ത്രമായും അവതരിപ്പിക്കുന്നു.'],
 ['Heard at Kathakali nights and in padam concerts.', 'കഥകളി രാത്രികളിലും പദക്കച്ചേരികളിലും.']),
'kummi': ('dance', 'Voice · Hand claps',
 ['Women dance in a circle, clapping and singing simple songs.', 'സ്ത്രീകൾ വട്ടത്തിൽ നിന്ന് കൈകൊട്ടി ലളിതമായ പാട്ടുകൾ പാടി ആടുന്നു.'],
 ['It is one of the oldest group dances of Kerala and Tamil Nadu, still enjoyed in villages.', 'കേരളത്തിലെയും തമിഴ്നാട്ടിലെയും ഏറ്റവും പഴയ സംഘനൃത്തങ്ങളിലൊന്ന്; ഗ്രാമങ്ങളിൽ ഇന്നും.'],
 ['Seen during Onam and Thiruvathira.', 'ഓണത്തിനും തിരുവാതിരയ്ക്കും.']),
'thumbithullal': ('dance', 'Voice · Hand claps',
 ['An Onam game where women sing around a girl holding thumba flowers, who sways faster and faster into a dance.', 'തുമ്പപ്പൂ പിടിച്ചിരിക്കുന്ന പെൺകുട്ടിക്കു ചുറ്റും സ്ത്രീകൾ പാടുമ്പോൾ അവൾ വേഗത്തിൽ ഉറഞ്ഞുതുള്ളുന്ന ഓണക്കളി.'],
 ['The thumbi is the dragonfly, and the songs call it to come and dance.', 'തുമ്പി എന്നാൽ തുമ്പി ഈച്ച; പാട്ടുകൾ തുമ്പിയെ തുള്ളാൻ വിളിക്കുന്നു.'],
 ['Played in homes during Onam.', 'ഓണക്കാലത്ത് വീടുകളിൽ.']),
'onathallu': ('sticks', 'Chenda · Voice',
 ['A mock fight played during Onam, with open-hand blows, rules and a referee.', 'നിയമങ്ങളും വിധികർത്താവുമായി തുറന്ന കൈകൊണ്ട് ഓണക്കാലത്ത് നടത്തുന്ന കളിയടി.'],
 ['It is an old Onam custom still kept alive at Kunnamkulam in Thrissur.', 'തൃശ്ശൂരിലെ കുന്നംകുളത്ത് ഇന്നും നിലനിൽക്കുന്ന പഴയ ഓണാചാരം.'],
 ['Played on the Onam days.', 'ഓണനാളുകളിൽ.']),
'onappottan': ('mask', 'Hand bell',
 ['A silent masked figure who walks from house to house in north Malabar during Onam, ringing a small bell.', 'ഓണക്കാലത്ത് ചെറിയ മണി കിലുക്കി വീടുതോറും നടക്കുന്ന, മിണ്ടാത്ത, മുഖംമൂടിയണിഞ്ഞ രൂപം.'],
 ["He is believed to bring Mahabali's blessings and never speaks.", 'മഹാബലിയുടെ അനുഗ്രഹവുമായി വരുന്നുവെന്നാണ് വിശ്വാസം; ഒരിക്കലും സംസാരിക്കില്ല.'],
 ['Seen in Kannur and Kozhikode villages on Uthradam and Thiruvonam.', 'ഉത്രാടത്തിനും തിരുവോണത്തിനും കണ്ണൂർ, കോഴിക്കോട് ഗ്രാമങ്ങളിൽ.']),
'kudamattam': ('chenda', 'Chenda · Elathalam · Kombu · Kuzhal',
 ['The exchange of bright parasols on elephants at Thrissur Pooram, done in time with the melam.', 'മേളത്തിന്റെ താളത്തിൽ ആനപ്പുറത്ത് വർണ്ണക്കുടകൾ മാറിമാറി ഉയർത്തുന്ന തൃശ്ശൂർ പൂരത്തിലെ ചടങ്ങ്.'],
 ['Paramekkavu and Thiruvambady compete with dozens of umbrellas, each set more dazzling than the last.', 'പാറമേക്കാവും തിരുവമ്പാടിയും ഡസൻകണക്കിന് കുടകളുമായി മത്സരിക്കുന്നു, ഓരോന്നും മുമ്പത്തേതിനേക്കാൾ മനോഹരം.'],
 ['The evening highlight of Thrissur Pooram at the Thekkinkadu Maidanam.', 'തേക്കിൻകാട് മൈതാനത്ത് തൃശ്ശൂർ പൂരത്തിന്റെ സന്ധ്യയിലെ പ്രധാന ആകർഷണം.']),
'ilanjithara': ('chenda', 'Uruttu chenda · Valanthala chenda · Elathalam · Kuzhal · Kombu',
 ['The great Pandi melam played under the Ilanji tree inside Vadakkunnathan temple during Thrissur Pooram.', 'തൃശ്ശൂർ പൂരത്തിന് വടക്കുന്നാഥക്ഷേത്രത്തിനുള്ളിലെ ഇലഞ്ഞിമരച്ചുവട്ടിൽ കൊട്ടുന്ന മഹത്തായ പാണ്ടിമേളം.'],
 ['Hundreds of musicians build it up over hours; it is one of the biggest moments in the melam world.', 'നൂറുകണക്കിന് കലാകാരന്മാർ മണിക്കൂറുകളോളം കൊട്ടിക്കയറുന്നു; മേളലോകത്തെ ഏറ്റവും വലിയ മുഹൂർത്തങ്ങളിലൊന്ന്.'],
 ['On Thrissur Pooram day, in the afternoon.', 'തൃശ്ശൂർ പൂരദിവസം ഉച്ചകഴിഞ്ഞ്.']),
'madathilvaravu': ('hand', 'Thimila · Maddalam · Elathalam · Edakka · Kombu',
 ["The famous Panchavadyam that leads Thiruvambady's procession from Naduvil Madhom on Thrissur Pooram morning.", 'തൃശ്ശൂർ പൂരദിവസം രാവിലെ നടുവിൽ മഠത്തിൽ നിന്നുള്ള തിരുവമ്പാടിയുടെ എഴുന്നള്ളിപ്പിന് മുന്നിലെ പ്രസിദ്ധ പഞ്ചവാദ്യം.'],
 ['Over a hundred artists take part, building through the kaalams as the elephants move.', 'നൂറിലേറെ കലാകാരന്മാർ ആനകൾക്കൊപ്പം നീങ്ങി കാലങ്ങൾ കയറ്റുന്നു.'],
 ['On Thrissur Pooram morning.', 'തൃശ്ശൂർ പൂരദിവസം രാവിലെ.']),
'seeveli': ('lamp', 'Chenda · Elathalam · Kombu · Kuzhal',
 ['The procession of the deity around the temple, on an elephant or carried, with melam.', 'ആനപ്പുറത്തോ കൈകളിലേന്തിയോ മേളത്തോടെ ക്ഷേത്രത്തിനു ചുറ്റും ദേവനെ എഴുന്നള്ളിക്കുന്നു.'],
 ['Held in the morning and evening of festival days, it is when devotees see the deity outside the sanctum.', 'ഉത്സവദിവസങ്ങളിൽ രാവിലെയും വൈകിട്ടും; ശ്രീകോവിലിനു പുറത്ത് ദേവനെ ദർശിക്കാനുള്ള അവസരം.'],
 ['Every day of temple festivals across Kerala.', 'കേരളത്തിലെ ക്ഷേത്രോത്സവങ്ങളിൽ എല്ലാ ദിവസവും.']),
'kodiyettam': ('lamp', 'Chenda · Thimila · Kombu · Shankh',
 ['Music for raising the festival flag on the temple flagstaff, the start of the utsavam.', 'ഉത്സവത്തിന്റെ തുടക്കമായി ക്ഷേത്ര കൊടിമരത്തിൽ കൊടി ഉയർത്തുമ്പോഴുള്ള വാദ്യം.'],
 ['Once the flag is up, the festival has begun and the whole village prepares for the days ahead.', 'കൊടി കയറിയാൽ ഉത്സവം തുടങ്ങി; ഗ്രാമം മുഴുവൻ വരുന്ന ദിവസങ്ങൾക്കായി ഒരുങ്ങുന്നു.'],
 ['The first day of temple festivals.', 'ക്ഷേത്രോത്സവങ്ങളുടെ ആദ്യദിവസം.']),
'aarattu': ('boat', 'Chenda · Elathalam · Kombu · Kuzhal · Nadaswaram',
 ['The procession taking the deity for a holy bath in a river or temple pond, ending the festival.', 'ഉത്സവത്തിന്റെ സമാപനമായി ദേവനെ പുഴയിലോ ക്ഷേത്രക്കുളത്തിലോ ആറാട്ടിന് കൊണ്ടുപോകുന്ന ഘോഷയാത്ര.'],
 ['The deity returns from the bath with melam and fireworks, and the festival flag is lowered.', 'മേളവും വെടിക്കെട്ടുമായി ആറാട്ട് കഴിഞ്ഞ് മടങ്ങുന്നു; കൊടിയിറങ്ങുന്നു.'],
 ['The last day of temple festivals, famous at Arattupuzha and Sabarimala.', 'ക്ഷേത്രോത്സവങ്ങളുടെ അവസാനദിവസം; ആറാട്ടുപുഴയിലും ശബരിമലയിലും പ്രസിദ്ധം.']),
'kettukazhcha': ('dance', 'Chenda · Nadaswaram · Thavil · Voice',
 ['Giant decorated chariots, horses and figures pulled to the temple by villagers in Onattukara.', 'ഓണാട്ടുകരയിലെ ഗ്രാമവാസികൾ ക്ഷേത്രത്തിലേക്ക് വലിച്ചുകൊണ്ടുവരുന്ന അലങ്കരിച്ച കൂറ്റൻ തേരുകളും കുതിരകളും രൂപങ്ങളും.'],
 ['Each kara (village area) builds its own figure, and the procession is a matter of great pride.', 'ഓരോ കരയും സ്വന്തം കെട്ടുകാഴ്ച ഒരുക്കുന്നു; ഘോഷയാത്ര വലിയ അഭിമാനമാണ്.'],
 ['At Chettikulangara Kumbha Bharani and other Onattukara temple festivals.', 'ചെട്ടികുളങ്ങര കുംഭഭരണിയിലും മറ്റ് ഓണാട്ടുകര ക്ഷേത്രോത്സവങ്ങളിലും.']),
'pallivetta': ('horn', 'Chenda · Kombu · Kuzhal · Elathalam',
 ['The ritual hunt of the deity on the night before Aarattu, symbolising victory over evil.', 'ആറാട്ടിന്റെ തലേരാത്രി തിന്മയ്ക്കു മേലുള്ള വിജയത്തിന്റെ പ്രതീകമായി ദേവൻ നടത്തുന്ന നായാട്ട്.'],
 ['The deity goes out in procession and an arrow is shot at a symbolic target.', 'ദേവനെ എഴുന്നള്ളിച്ച് പ്രതീകാത്മക ലക്ഷ്യത്തിലേക്ക് അമ്പെയ്യുന്നു.'],
 ['On the night before Aarattu in many temple festivals.', 'പല ക്ഷേത്രോത്സവങ്ങളിലും ആറാട്ടിന്റെ തലേന്ന് രാത്രി.']),
}
